
#Server Settings
server:
  port: 8080

spring:
  #DataSource Settings
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/h2
    username: kko
    password: 1234


  #H2 Settings
  h2:
    console:
      enabled: true
      path: /kko-pay
      settings:
        trace: true
        web-allow-others: false

  #JPA Settings
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
